### PR TITLE
added one space :))

### PR DESCRIPTION
**Pull request by pleycpl**

### CODE REVIEW

**Comment by piranna** [comment]
Can you explain the change?

**Comment by pleycpl** [comment]
In "https://github.com/NodeOS/NodeOS/blob/master/README.md#build-nodeos-in-five-steps"  section, 
3., 4. and 5. step is confused code displaying. I think there is problem from 3.step '```' characters.

**Comment by piranna** [comment]
You are right, good eye! :-) The other change on the empty line is not needed, can you remove it?

**Comment by pleycpl** [comment]
I'm sorry, I removed it.

**Comment by piranna** [comment]
Merged :-)

**Pull request merged**
