### PR TITLE
updating FUSE_URL

### PR DESCRIPTION
**Pull request by frankstein-1**
fuse is no more available in sourceforge

### CODE REVIEW

**Comment by piranna** [comment]
Good catch, I surpassed this absolutely! How did you noticed it?

**Comment by frankstein-1** [comment]
Because of this error message.
```
> nodeos-initramfs@0.0.0 preinstall /home/user/nodeos/NodeOS/node_modules/nodeos-initramfs
> scripts/preinstall

Downloading fuse... 
/home/user/nodeos/NodeOS/node_modules/nodeos-initramfs/scripts/preinstall:33
  if(error) throw error;
            ^
HTTPError: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (/home/user/nodeos/NodeOS/node_modules/download-manager/node_modules/got/index.js:184:24)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at Immediate._onImmediate (/home/user/nodeos/NodeOS/node_modules/download-manager/node_modules/got/index.js:54:8)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

npm ERR! Linux 3.13.0-37-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! nodeos-initramfs@0.0.0 preinstall: `scripts/preinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodeos-initramfs@0.0.0 preinstall script 'scripts/preinstall'.
npm ERR! This is most likely a problem with the nodeos-initramfs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripts/preinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodeos-initramfs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/nodeos/NodeOS/npm-debug.log
```

**Comment by piranna** [comment]
Thank you for finding it! It was several days that I don't do a full compilation from scratch...

**Comment by frankstein-1** [comment]
I got others messages. like 
```
Setup is 16092 bytes (padded to 16384 bytes).
System is 5490 kB
CRC d49655db
Kernel: arch/x86/boot/bzImage is ready  (#1)
make[1]: Leaving directory `/home/user/nodeos/NodeOS/node_modules/nodeos-barebones/obj/nocona/linux'
Timeout while waiting an answer

npm ERR! Linux 3.13.0-37-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! nodeos-barebones@0.0.0 install: `scripts/build`
npm ERR! Exit status 50
npm ERR! 
npm ERR! Failed at the nodeos-barebones@0.0.0 install script 'scripts/build'.
npm ERR! This is most likely a problem with the nodeos-barebones package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripts/build
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodeos-barebones
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/nodeos/NodeOS/npm-debug.log
```
and
```
Finished
make[1]: Leaving directory `/home/user/nodeos/NodeOS/node_modules/nodeos-barebones/deps/node/out'
ln -fs out/Release/node node
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn qemu-x86_64 ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:136:18)
    at node.js:963:3

npm ERR! Linux 3.13.0-37-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! nodeos-barebones@0.0.0 install: `scripts/build`
npm ERR! Exit status 15
npm ERR! 
npm ERR! Failed at the nodeos-barebones@0.0.0 install script 'scripts/build'.
npm ERR! This is most likely a problem with the nodeos-barebones package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripts/build
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodeos-barebones
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/nodeos/NodeOS/npm-debug.log
```
Now, I have a kernel panic. I'll rebuild and see

**Comment by piranna** [comment]
The second one is because you don't have installed the qemu-user package. The first one I've also see it on the server lately but didn't have time to take an intensive look there to know what's happening... :-/

**Comment by frankstein-1** [comment]
so, why you don't add qemu-user to depends list ?

**Comment by piranna** [comment]
It should be added, it needs to be installed on the server too...

**Pull request merged**
