### PR TITLE
Fixed browse_from_source.md Link in docs

### PR DESCRIPTION
**Pull request by citrix123**
The link gives 404 error previously on git hub.

### CODE REVIEW

**Comment by citrix123** [comment]
Can any one review this ?

**Comment by luii** [comment]
If i had write access i would merge it.
@piranna would you be so kind to merge it?

**Comment by piranna** [comment]
I'm too busy lately due to work and don't seems to decrease in the future, sorry.

**Comment by citrix123** [comment]
@piranna 
What are the future plans with this project ?
I am happy to help :100:

**Pull request merged**
