### PR TITLE
Fixing typos & updating stats

### PR DESCRIPTION
**Pull request by lite20**
I updated a few statistics like the npm count of packages since it is relatively bigger now, and additionally corrected a few typos I came across as I browsed. Hopefully I'll be able to migrate a bit of info to the wiki and make this Readme a bit smaller and more friendly to newcomers.

### CODE REVIEW

**Comment by piranna** [comment]
Forgot about this, sorry :-P

**Comment by lite20** [comment]
All good! Hahah

**Comment by piranna** [comment]
;-) When we launch the 1.0 release we'll need to look into split NodeOS in several subprojects specially the cross-compiler, it's too much heavy and almost all the build errors comes from there... :-/

**Comment by lite20** [comment]
@piranna hahaha that's a good idea!

**Comment by piranna** [comment]
We could start by packaging an publishing noGUI and later do the same with GCC and QEmu.

**Comment by Coretool** [comment]
The binaries are stored on github, right ?

**Comment by lite20** [comment]
@Coretool which binaries?

@piranna I'm forking and going to attempt to rip QEmu out of the build process.

**Comment by Coretool** [comment]
@lite20 the prebuilt ones

**Comment by piranna** [comment]
> @Coretool which binaries?
> @lite20 the prebuilt ones

The only prebuild binaries that are currently available are NodeOS prebuild images, we would need to publish the QEmu and gcc ones using the `prebuild` module I told you the other day. This could have the advantage that would allow to install a working version of gcc inside NodeOS and allow to install compiled modules... :-) But it will need some work to get to that point, being the first step to make the cross-compiler an independent module and use it as dependency of nodeos-barebones.

**Comment by Coretool** [comment]
What makes the cross-compiler 'special' ?

**Comment by Coretool** [comment]
It looks pretty independent from my point of view ... (I am refering to the nodeos-cross-toolchain repo). Do you just want it to be a(-nother) prebuilt package ? Or do you want to make gcc a prebuilt package ? (Or even both)

**Comment by piranna** [comment]
> What makes the cross-compiler 'special' ?

Nothing itself, only the point that if we set it as dependency of all the layers, it would be installed several times... but if we create prebuild images, this would not be a huge problem because we would not spend time generating it several times.


> It looks pretty independent from my point of view ... (I am refering to the nodeos-cross-toolchain repo). Do you just want it to be a(-nother) prebuilt package ? Or do you want to make gcc a prebuilt package ? (Or even both ?)

I'm thinking only about nodeos-cross-toolchain, having inside gcc, binutils and friends pre-generated for all the platforms NodeOS is ported, somewhat similar to how it's packaged on regular Linux distros, only that this package would all *all* the cross-toolchain. with compiler, linker, libraries... Don't remember if there's already a cross-toolchain repo, but if so it will be outdated, so we would need to update its content. Would you be able to point us to what have you found?

**Comment by Coretool** [comment]
It's at github.com/nodeos/nodeos-cross-toolchain... This repo just contains the build scripts, I think... So you wanna create a prebuilt package with all the build utils and their friends and families (...) Sounds great... ;)

**Comment by piranna** [comment]
> It's at github.com/nodeos/nodeos-cross-toolchain... This repo just contains the build scripts, I think...

I supposed so... This repo is one year ago, it needs to get updated, but yes, it's the correct one :-) You could start working on it if you want and later I'll update it, this way we don't loose the commits history :-)


> So you wanna create a prebuilt package with all the build utils and their friends and families (...) Sounds great... ;)

Yes, and this one could also be used to install native modules inside of NodeOS or being use as basis for other cross-compiled related projects making them easier to use :-)

**Comment by lite20** [comment]
>> What makes the cross-compiler 'special' ?
> Nothing itself, only the point that if we set it as dependency of all the layers, it would be installed several times...

Oh. Could we not have the scripts install it globally? Or have the modules arranged in a way where the path of it could be fetched relatively? (navigate from current location say to the nodeos node modules folder where it's expected to be, and import from there)

Just an idea for that issue.

**Comment by Coretool** [comment]
>Or have the modules arranged in a way where the path could be fetched relatively

That's what *I* thought about too... Which platforms should these prebuilt packages support ?

**Comment by piranna** [comment]
> Could we not have the scripts install it globally?

npm don't support this and never will do, sorry :-(


> Or have the modules arranged in a way where the path of it could be fetched relatively?

Yeah, I was thinking about using this solution, some modules like `phantomjs` does it :-) We could put it (by the moment) as a direct dependency of `nodeos` module the same way as the different layers. I didn't do it before because they are resolved in alphabetical order and the championship needed to have only one repository, but since external dependencies in a same level are fetched and processed before the included ones, this could work... :-)


> I'll start compiling some binaries today, which platforms should these prebuilt binaries support ?

By the moment only the ones supported by NodeOS, it's said, linux i686 and linux x86_64, both as host and target. This will lead to having two packages, one for i686 and other for x86_64 (that the host platform, and each one will contain binaries to generate for i686 and x86_64 thenselves).

**Comment by Coretool** [comment]
So I'll make a normal gcc binary first, are there any things I have to look at ?

**Comment by piranna** [comment]
`nodeos-crosscompiler` module is somewhat autonomous and independent. By default it detect the platform where is running and generate a cross-compiler for itself, so start it (just `npm install`). You can be able to set different platforms and CPUs using environment variables, take a look at `scripts/adjustEnvironment.sh` to generate both the i686 and x86_64 versions. After that, they'll be generated on the `out` folder, would be good to add a `.npmignore` file with everything except that folder. Finally you could publish this package on npm but it will be too heavy, so it's better you take a look about how to publish it on GitHub using `prebuild`.

I think I've not left anything... :-P

**Comment by Coretool** [comment]
Then let the compilation begin ;) 

Publishing to github using prebuild isn't hard; it's just `prebuild --upload`


Afterwards, we have to add `prebuild --install` to the package.json's install command...

**Comment by piranna** [comment]
Woah! :-D When you get it working create a repo for it and publish the prebuild images there, later we'll see how to organize it :-)

**Pull request merged**
