### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by WhySoSeriousMORI**

### CODE REVIEW

**Comment by piranna** [comment]
Thank you :-)

**Comment by WhySoSeriousMORI** [comment]
Could I say contributed in NodeOS?

**Comment by piranna** [comment]
Sort of.

**Comment by WhySoSeriousMORI** [comment]
So I'm ready to go for a job interview now. Bye!

**Comment by piranna** [comment]
> So I'm ready to go for a job interview now. Bye!

That's not fair, and you know it. F*ck yourself :angry:

**Comment by aulvi** [comment]
@piranna Let's keep it clean and respectful please.

**Comment by piranna** [comment]
> @piranna Let's keep it clean and respectful please.

Yeah, I'm sorry for my distasteful response, but being ironic or not, that an empty profile without a background just fix a typo and want to go for a job interview as NodeOS commiter, although it's true, it's not professional by trying to get some benefict and reputation from the work of others.

**Comment by piranna** [comment]
I'll try to moderate my tone in the future and not take some sort of things as personal offenses, I promise.

**Comment by aulvi** [comment]
@piranna Thank you, you're a hugely important part of this project and therefore your words have a lot of weight.

Honestly, if this contributor is able to convert a single contribution into a paying job then I would be more impressed than upset.

**Comment by lite20** [comment]
Cleaned thread. Locking.

**Pull request merged**
