### PR TITLE
Use layers as npm dependencies

### PR DESCRIPTION
**Pull request by piranna**
Work in progress - don't merge yet.

I have tried to split each layer at node_modules folder on it's own project and fetch them using npm, but seems they are not processed in order so inter-layer dependencies are not meet. I think only solution would be to wait until npm@3 implement the multi-stage install process and more specifically the dedupe functionality (flat dependencies hierarchy) by default, so this way the cross-compiler would be set as a dependency of all the packages and it would be installed first without duplication, whatever its the first one to be processed. The same would apply for the inter-layer dependencies, so it would force the others to be processed first.

### CODE REVIEW

**Comment by lite20** [comment]
Is this still active?

**Comment by piranna** [comment]
> Is this still active?

More than ever, nodeos-cross-toolchain was just the first one, and now that
it's ready the other will be trivial to do :-D

**Comment by lite20** [comment]
Okie dokie! hahaha

**Comment by piranna** [comment]
;-)

**Comment by piranna** [comment]
This was already done on master, so it made sense to merge or deprecate it :-P

**Pull request merged**
