### PR TITLE
Cross compiler musl

### PR DESCRIPTION
**Pull request by piranna**
This is a work-in-progress pull-request just so we can comment on it.

Finally I've managed to create a cross-toolchain and use it to compile a runnable NodeOS instance (i386-glibc -> i686-musl, I need to test x86_64 -> i386). After some tries, I got it to work using as basis [Cross Linux From Scratch - Embedded](http://clfs.org/view/clfs-embedded), that uses [musl](http://www.musl-libc.org/) as C lib instead of standard glibc. I wanted to use a glibc based system, but this is the only one I've managed to make it to work, since using the plain [Linux From Scratch](http://www.linuxfromscratch.org/) or also the standard [Compressed Linux From Scratch](http://www.clfs.org/view/CLFS-3.0.0-SYSVINIT/) (both based on glibc) was fairly overcomplicated and gave a lot of compilation problems.

This has some drawbacks that needs improvement (or not :-) ):

* it's a musl based system, so compiled modules that use non-standard extensions of GNU glibc will not compile. It's a fail of the developers, so this could help to improve their code to be C standard compliant (win-win for all :-) ).
* OpenSSL doesn't work well with musl (due to the use of that non-standard extensions...) and needs to be patched since [nobody](https://rt.openssl.org/Ticket/Display.html?id=2823&user=guest&pass=guest) [fix](https://rt.openssl.org/Ticket/Display.html?id=3526&user=guest&pass=guest) [it](https://rt.openssl.org/Ticket/Display.html?id=3123) :-( Luckily [it's an easy one](https://raw.githubusercontent.com/maximeh/buildroot/master/package/openssl/openssl-004-musl-termios.patch)...
* GCC is not aware of musl so [it needs to be patched](http://patches.clfs.org/embedded-dev/gcc-4.7.3-musl-1.patch), too. This leads us to use a fixed GCC version, but since it's somewhat new (April 2014) and probably we'll move to [llvm](http://llvm.org/) when [Linux could be compiled with it](http://llvm.linuxfoundation.org/) so we can use one of the llvm [Javascript](http://badassjs.com/post/39573969361/llvm-js-llvm-itself-compiled-to-javascript-via) [flavours](http://leaningtech.com/cheerp/) on the userspace, then it's a fair trade by this moment.
* I was not be able to use a dynamically linked Node.js executable, so I'm using a [fully-statically linked](https://github.com/joyent/node/pull/8274) one. This should be fixed in the future for loading of compiled modules and specially to exec binaries, but if we don't allow binaries at all and since now ```require()``` of modules works because musl now include the required ```dl_``` functions (at least native ones does while it was not working before, I need to test external ones), this could help to enforce a pure-Javascript environment :-) On the other hand, this also has the advantage that the memory foot-print is smaller since now the only required files on the initramfs are the console device and the Node.js executable (impossible to make it simpler!!! :-D )

It's still unstable and needs some more work and testing (please test it! :-D ), but when it's finished, NodeOS build system will be self-contained and will be easier to port it to other platforms just by updating the cross-compiler :-) Also I've been developing it as a NPM package, so when it's ready in the future we could be able to move it to be an independent project (I would love to see NodeOS self-hosted... :-D ).

### CODE REVIEW

**Comment by netlovers** [comment]
If only the `chroot()` function is needed then it should be quite easy to make a node 0.11 compatible version. Actually I just did that. The `node-posix` test file runs with it. But I guess it is possible to rewrite all the posix module. I'll have to check what other modules don't work, and see if it is easy to convert them.

**Comment by netlovers** [comment]
Man, there are some really confusing parts about this. I already made a bunch of native modules work with node 0.11, but I noticed that there is this `"src-sockios": "~0.1.0"` in a `package.json` file. And compiling it eats away all of my computer's memory. I checked it, and the `0.1.0` looks like not even `src-sockios` but `src-ifaddrs`.
Download this and you'll see: http://registry.npmjs.org/src-sockios/-/src-sockios-0.1.0.tgz
I'm beginning to wonder if this ever worked.

**Comment by netlovers** [comment]
Compiling works now, but I'm not sure how the directories and files should show up. It says:
```
sd 0:0:1:0: [sdb] Attached SCSI disk
sd 0:0:0:0: [sda] Attached SCSI disk
```
So I guess it works...? There is no visible sign of errors.

**Comment by piranna** [comment]
> Man, there are some really confusing parts about this. I already made a
bunch of native modules work with node 0.11, but I noticed that there is
this "src-sockios": "~0.1.0" in a package.json file. And compiling it eats
away all of my computer's memory. I checked it, and the 0.1.0 looks like
not even src-sockios but src-ifaddrs.
> Download this and you'll see:
http://registry.npmjs.org/src-sockios/-/src-sockios-0.1.0.tgz
> I'm beginning to wonder if this ever worked.

This are some packages for network support that @groundwater did, but I
didn't take a look on them yet, so don't know what's their status, sorry :-(

**Comment by piranna** [comment]
> Compiling works now, but I'm not sure how the directories and files
should show up. It says:
>
> sd 0:0:1:0: [sdb] Attached SCSI disk
> sd 0:0:0:0: [sda] Attached SCSI disk
>
> So I guess it works...? There is no visible sign of errors.

I think these lines are of Linux kernel itself, since it has detected the
hard disk drives. Do you see a prompt at the bottom or some message? What
says it?

**Comment by netlovers** [comment]
There is a century prompt, but then I do:
```
> var fs = require('fs');
> fs.readdirSync('.')
[ 'bin', 'dev', 'init', 'lib', 'sbin', 'usr' ]
```
But the userfs and rootfs does not seem to be there (in any of the directories).

**Comment by piranna** [comment]
> There is a century prompt, but then I do:
>
> > var fs = require('fs');
> > fs.readdirSync('.')
> [ 'bin', 'dev', 'init', 'lib', 'sbin', 'usr' ]
>
> But the userfs and rootfs does not seem to be there (in any of the
directories).

Obviously, that's why I asked for the prompt, because they are in order :-D
century execs /sbin/init, that's a symlink to nodeos-mount-rootfs, if you
got a century prompt, it happened an error when trying to execute it.
Nodeos-mount-rootfs was commented on nodeos-initramfs/packages.txt because
it didn't compile, if you've managed to compile it with v0.11.14 then by
uncommenting it should work :-)

Do you have your changes uploaded somewhere to take a look, or are you
still testing it?

**Comment by netlovers** [comment]
I uncommented that. Otherwise there would be no `rootfs.img`. I'm still testing it, but will upload it in a few hours.

**Comment by piranna** [comment]
Ok, great :-)

**Comment by netlovers** [comment]
Yay, the rootfs seems to be working. My prompt says `NodeOS-mount-rootfs>`. You can use this patch to try it out, and work on it more: https://gist.github.com/netlovers/2d8d68ccf781f11520ae

**Comment by netlovers** [comment]
And yay, usersfs is working too `NodeOS-usersfs>`. A link was set up incorrectly. Updated my patch to fix this too.

**Comment by netlovers** [comment]
Okay, no the usersfs is not working, only the prompt says so. But there is an error:
```
Error re-mounting / as read-only
Error No error information while mounting /home
-1
```

**Comment by piranna** [comment]
Ok, with your changes the root filesystem is loaded correctly, it keeps the users filesystem, but should be the same as with the root one. Instead of a patch I was asking for a fork, but that's ok too :-)

The error messages that you see are of the ```src-mount``` module, they are not too clear so I was thinking about improve them by using https://github.com/NodeOS/node-mount and also add support for auto detection of the filesystem so it doesn't need to be hardcoded.

**Comment by netlovers** [comment]
To be honest, I don't really like forks. They get outdated fast, and nobody supports them. So I keep forked repos as long as I need them. And I wasn't planning on working on this, I just help out a bit, so the project can move on.
`node-mount` looks nice, but it needs converting too.

**Comment by piranna** [comment]
> To be honest, I don't really like forks. They get outdated fast, and nobody supports them. So I keep forked repos as long as I need them. And I wasn't planning on working on this, I just help out a bit, so the project can move on.

The advantage of the fork is that it's easier to do a pull-request
later :-D I was thinking to do forks of all dependencies under the
NodeOS organization here at GitHub so we can control better the
specific versions.


> node-mount looks nice, but it needs converting too.

Didn't though about it would need to be converted, too... :-/ I'll
improve and clean it. Is it easy to do the conversion?


-- 
"Si quieres viajar alrededor del mundo y ser invitado a hablar en un
monton de sitios diferentes, simplemente escribe un sistema operativo
Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by netlovers** [comment]
Check out the logs for my forks of the NodeOS dependencies, and you'll see. Nan really helps there, and it supposed to work on almost every node version. But `node-mount` is a bit more complicated, mainly because of this: `uv_work_t`. It needs a bit more magic to make it work, something like this:
https://github.com/soundrop/mmmagic/commit/1807be2f0e7fba44801927b482e5e9370fb710d4#diff-efc0867fe5f4d1c84445b06f9eb02d17R217

**Comment by netlovers** [comment]
By the way, the patch is only related to this pull request, I forked every other module, to make them work (just in case you didn't notice).

**Comment by piranna** [comment]
> Check out the logs for my forks of the NodeOS dependencies, and you'll see. Nan really helps there, and it supposed to work on almost every node version. But node-mount is a bit more complicated, mainly because of this: uv_work_t. It needs a bit more magic to make it work, something like this:
> soundrop/mmmagic@1807be2#diff-efc0867fe5f4d1c84445b06f9eb02d17R217

The uv work tasks are created to exec the mount() function in a
different thread and make it asynchronous. I'm totally new to code
compiled modules, so I can't say here... :-/

I've cleaned node-mount code and added support for optional parameters
and autodetection of filesystem, you can get it at
https://github.com/NodeOS/nodeos-mount, I've added you commit
permissions. If you want, I can move your forks to NodeOS organization
and give you commit permissions too, so you don't need to administer
them yourself, and also we can have them managed on only one place :-)


-- 
"Si quieres viajar alrededor del mundo y ser invitado a hablar en un
monton de sitios diferentes, simplemente escribe un sistema operativo
Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by piranna** [comment]
> By the way, the patch is only related to this pull request, I forked every other module, to make them work (just in case you didn't notice).

Yeah, I saw them :-D


-- 
"Si quieres viajar alrededor del mundo y ser invitado a hablar en un
monton de sitios diferentes, simplemente escribe un sistema operativo
Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by netlovers** [comment]
> I've added you commit permissions. If you want, I can move your forks to NodeOS organization and give you commit permissions too, so you don't need to administer them yourself, and also we can have them managed on only one place :-)

Ohh, great! Thanks! :)
Yeah, I think it would be best if all the modules were under the NodeOS organization. But we have to agree on a naming convention. Because right now some modules start with `node-bin-`, `node-src-`, `nodeos-`, and `NodeOS-`. And there is for example the `NodeOS-mount-usersfs` and it's package.json says `nodeos-usersfs` so good luck finding it.

**Comment by piranna** [comment]
> Ohh, great! Thanks! :)

You are welcome ;-) It's the best way to integrate your changes :-)


> Yeah, I think it would be best if all the modules were under the NodeOS organization. But we have to agree on a naming convention. Because right now some modules start with node-bin-, node-src-, nodeos-, and NodeOS-. And there is for example the NodeOS-mount-usersfs and it's package.json says nodeos-usersfs so good luck finding it.

node-bin-mount and node-src-mount will be deprecated when we use
NodeOS-mount, since it's more versatile and node-like. For the others,
I think we could prefix all of them as NodeOS- on GitHub, and
nodeos-on NPM (it requires all names to be lowercase), and also add
NodeOS as a keyword on package.json so they can be easily searchable.


-- 
"Si quieres viajar alrededor del mundo y ser invitado a hablar en un
monton de sitios diferentes, simplemente escribe un sistema operativo
Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by netlovers** [comment]
I think lowercase names are better, because `git clone` can be used easier (no need for the fourth param).
By the way, I'm almost finished with the `nodeos-mount` conversion, the test runs just fine except I can't seem to get the error messages right. There is the `node::ErrnoException` but everytime I call it the whole thing just segfaults. Which means that some of my previous attempts at converting may be wrong too.

**Comment by piranna** [comment]
> I think lowercase names are better, because git clone can be used easier (no need for the fourth param).

Everything lowercase, you say? Also the name of the GitHub projects?


> By the way, I'm almost finished with the nodeos-mount conversion, the test runs just fine except I can't seem to get the error messages right. There is the node::ErrnoException but everytime I call it the whole thing just segfaults. Which means that some of my previous attempts at converting may be wrong too.

That's great! :-D Well, one step at a time, if there are problems with
the conversion we can check the other projects later to find them :-)


-- 
"Si quieres viajar alrededor del mundo y ser invitado a hablar en un
monton de sitios diferentes, simplemente escribe un sistema operativo
Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by piranna** [comment]
I was thinking to add a CLI ```mount``` tool to ```nodeos-mount```, but seems [it's really a complex command](http://linux.die.net/man/8/mount) that maybe it's better to be in an independent package using ```nodeos-mount``` as a library dependency, so I'll left this to be done later in the future.

**Comment by netlovers** [comment]
I think the organization name fine with camelcase, and maybe the `NodeOS` project itself too. But the submodules that later going to be uploaded to npm would be better with all lowercase names, and that name should be in the `package.json` too. But this all is not really related to the pull request, and it was just an idea to at least have some sort of convention for these things.

**Comment by piranna** [comment]
> I think the organization name fine with camelcase, and maybe the NodeOS project itself too. But the submodules that later going to be uploaded to npm would be better with all lowercase names, and that name should be in the package.json too.

Ok, then we'll put them on lowercase nodeos- to make them equal both
on GitHub and NPM, and we'll left the organization and the main
project as NodeOS since it will not be capable to set as dependency as
itself (and in fact I've set it as private so it can't be added to NPM
registry).


> But this all is not really related to the pull request, and it was just an idea to at least have some sort of convention for these things.

It's not directly related to the pull-request, but we can do it, when
it got to be working and merged :-)


-- 
"Si quieres viajar alrededor del mundo y ser invitado a hablar en un
monton de sitios diferentes, simplemente escribe un sistema operativo
Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by netlovers** [comment]
Do you need the sync version for the `nodeos-mount` methods too? Or just the async is fine?

**Comment by piranna** [comment]
> Do you need the sync version for the nodeos-mount methods too? Or just the async is fine?

Just the async, really. I updated the sync one just for coherence.


-- 
"Si quieres viajar alrededor del mundo y ser invitado a hablar en un
monton de sitios diferentes, simplemente escribe un sistema operativo
Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by netlovers** [comment]
Okay, then I'll send a pull request in a few minutes. The error message is still not solved, but some cryptic message is fine until we figure out how to make it work.

**Comment by piranna** [comment]
Great ;-)

2015-01-02 16:03 GMT+01:00 Csaba Szabo <notifications@github.com>:

> Okay, then I'll send a pull request in a few minutes. The error message is
> still not solved, but some cryptic message is fine until we figure out how
> to make it work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NodeOS/NodeOS/pull/89#issuecomment-68532309>.
>



-- 
"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by piranna** [comment]
```Javascript
USERS filesystem not defined
Starting REPL session
NodeOS-mount-usersfs> 
```

Ok @netlovers, after your changes on [nodeos-mount](https://github.com/NodeOS/nodeos-mount/pull/1) to allow it to work with Node.js 0.11.14 and a lot of minor fixes and clean-ups to port the other mount modules to it, finally it works!!! :-D Now I'm getting build errors with ```src-errno```, ```src-sockios``` and ```src-ifaddrs```, that seems are related to ```bin-ifconfig```. Since networking seems to not work and needs a huge review, I've commented that package and the build process finish :-) I'm having problems to mount the users filesystem, but since the root filesystem gets mounted and both are similar, probably is a minor issue. I'll left this pull-request open until it gets fixed, and also I wanted to do some clean-ups on the build scripts and be sure that I can build the 32 bits version from my 64 bits machine and also a 64 bits pure version.

By the way, what machine are you using to compile NodeOS?

**Comment by netlovers** [comment]
64 bit (Windows 8.1), but I use VMware, so I can test it on either 32 and 64 bit.
Did you use my `node-bin-ifconfig` fork? I think that should work, at least last time it did.

**Comment by piranna** [comment]
I didn't say it, sorry :-P Ok, by using it now there are no build errors, thank you! :-D And another thing...

```
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: bin/users-services
Welcome to NodeOS!: username:  nodeos
Welcome to NodeOS!: password:  
```

Woah, now it has loaded the users filesystem! :-D It should have been the NPM cache the reason why it didn't worked... :-P

I asked about the machine because I didn't know if you were already testing it on 64bits :-P

**Comment by netlovers** [comment]
Cool! What's left? Or what are the further plans?

**Comment by piranna** [comment]
First fix a permissions bug related to /usr/bin/env (I don't know why it's failing now...) so logon can work, and after that testing that a 64 bits machine can build a 32 bits and a native 64 bits version, and maybe an arm version too (for Raspberry Pi :-P ). After that, re-enable network support is [one of the bigger priorities](https://github.com/NodeOS/NodeOS/issues/37)... :-)

**Comment by piranna** [comment]
Ok, ```/usr/bin/env``` fixed... and found that the problem why ```logon``` not loaded before was a race condition X-D Since now ```node-mount``` is totally asynchronous, then sometimes the ```/proc``` is not ready :-P Two options: add sync version, or use async.js to manage them.

Or promises!!! Hell yeah, we are using Node.js 0.11!!! :-D

**Comment by piranna** [comment]
```Javascript
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: bin/users-services
Welcome to NodeOS!: username:  nodeos
Welcome to NodeOS!: password:  
/home/nodeos # ls
[ 'bin', 'etc', 'init', 'lib', 'share' ]
/home/nodeos # ls /
fs.js:691
  return binding.readdir(pathModule._makeLong(path));
                 ^
Error: EACCES, permission denied '/'
    at Error (native)
    at Object.fs.readdirSync (fs.js:691:18)
    at Object.<anonymous> (/home/nodeos/lib/node_modules/bin-fs/bin/ls:12:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:124:16)
    at node.js:842:3
/home/nodeos # pwd
/home/nodeos
/home/nodeos # node
> 1 + 1
2
> 
```

Ouh yeah... B-)

**Comment by piranna** [comment]
barebones compiled on x86_64 for an i686 target :-) Other layers fails due to node-gyp trying to compile to 64 bits, probably an easy one :-D

**Comment by piranna** [comment]
Yes, [it was an easy one](https://github.com/TooTallNate/node-gyp/blob/d62787edf8b48fdf9b9813f535c62cf27783c76b/lib/configure.js#L205-L206) :-D Confirmed generation of i686 image from x86_64 architecture, but the async mounts are giving the race condition problems, specially because this host machine is fairly faster that the old one I was using :-/

Anyway, to generate it exec ```PLATFORM=qemu_32 npm install```. F*ck yeah!!! :-D

**Comment by netlovers** [comment]
I'll convert the sync mount functions in a few hours, when I'll have some more time.

**Comment by piranna** [comment]
:+1:

**Comment by netlovers** [comment]
Sent a pull request. I think it should work.

**Comment by piranna** [comment]
```Javascript
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: bin/users-services
Welcome to NodeOS!: username:  nodeos
Welcome to NodeOS!: password:  
/home/nodeos # ls
[ 'bin', 'etc', 'init', 'lib', 'share' ]
/home/nodeos # node
> Date()
'Tue Jan 06 2015 23:53:55 GMT+0000 (GMT)'
> 
```

NOW it is ;-) It has been a pain in the *ss, but now they mount correctly, and doing it cross-compiled. Honestly, using async.js instead of trying to use the sync function would have been easier... ;-)

Anyway, thank you so much for the hard job @netlovers!!! :-D Support for native 64 bits is half-done, I started it by accident and crashed on the generation of the cross-toolchain, we can see it in another issue.

**Comment by formula1** [comment]
You guys are freaking awesome!!!! I'm stoked.

**Pull request merged**
