### PR TITLE
Refactored functions to Arrow functions

### PR DESCRIPTION
**Pull request by Aakash1103Jha**
- changed `function() {}` to arrow function form.
- using destructuring for module imports.

### CODE REVIEW

**Comment by piranna** [comment]
Destructuring module imports, ok, thanks. Change functions to arrow functions just for the shake of it, definitely no.

**Comment by Aakash1103Jha** [comment]
Should I then undo the modification to function and leave the destructuring? And then open another PR? @piranna

**Comment by piranna** [comment]
Undo, and also left the two-spaces indentation.

**Comment by Aakash1103Jha** [comment]
> Undo, and also left the two-spaces indentation.

meaning, undo all my changes? @piranna

**Pull request closed without merging**
