### PR TITLE
Fix another typo

### PR DESCRIPTION
**Pull request by lite20**
Found a typo while reviewing. Man this is a long document. Here's the fix :stuck_out_tongue:

### CODE REVIEW

**Comment by piranna** [comment]
I've seen **really** long Readme files... :-P Here there are two options, add all the info inside, or left only the basic one and point to where is the in-detail docs.

**Comment by lite20** [comment]
@piranna yes I'm working toward the second one. Just need to find when I have time to sit down and write docs :P

At the moment, I'm going to try to finish removing QEMU

**Comment by piranna** [comment]
Ok. If you only remove it and don't create a npm package, you'll need to install it globally using apt.

**Comment by lite20** [comment]
> Ok. If you only remove it and don't create a npm package, you'll need to install it globally using apt.

Yes I have it globally installed. Shouldn't we make it a prerequisite that users install qemu before building NodeOS?

**Comment by piranna** [comment]
> Yes I have it globally installed. Shouldn't we make it a prerequisite that users install qemu before building NodeOS?

It was, but I decided to compile QEmu to remove that pre-requisite to the users to make it simpler to use, and also to be able to use the Raspberry Pi patches. Do you think we should remove it and query the user to have it globally installed again? I think it would be better to package it in a npm package and just set it as a dependency...

**Comment by Coretool** [comment]
@piranna I think installing qemu id a taskk that every user should be able to perform since every (or nearly every) platfrom got qemu (or a qemu port)

**Comment by piranna** [comment]
> @piranna I think installing qemu id a taskk that every user should be able to perform since every (or nearly every) platfrom got qemu (or a qemu port)

Not in NodeOS, if we want it to be self-hosted... :-D

**Comment by lite20** [comment]
> It was, but I decided to compile QEmu to remove that pre-requisite to the users to make it simpler to use, and also to be able to use the Raspberry Pi patches. Do you think we should remove it and query the user to have it globally installed again? I think it would be better to package it in a npm package and just set it as a dependency...

We could try to do that, but that would be one massive npm package. Would we aim to support all platforms?

**Comment by lite20** [comment]
I'm not sure if I'm removing QEMU in the right places but I can't even run the build scripts to test if it works as they're buggy. Which modules, someone please remind me, attempt to work with the QEMU build?

**Comment by piranna** [comment]
> We could try to do that, but that would be one massive npm package.

We can use [prebuild](https://www.npmjs.com/package/prebuild) to publish them on GitHub.


> Would we aim to support all platforms?

No, only the ones that are supported by NodeOS or are planned in a short time, it's said: x86, x86_64 and raspberry pi.

**Comment by piranna** [comment]
> Which modules, someone please remind me, attempt to work with the QEMU build?

For testing, it should be used only on nodeos-barebones, but it's used in all of them as part of `npm start` script to run it in a virtual machine (obviously :-D ).

**Comment by lite20** [comment]
Ah okay. I've removed the building of it but the other scripts would expect it to already exist. PR updated.

**Pull request merged**
