### PR TITLE
new wiki

### PR DESCRIPTION
**Pull request by lite20**
Add link to under-construction new wiki.

### CODE REVIEW

**Comment by piranna** [comment]
Any update on this? Where is the doc published? Should we remove the docs folder?

**Comment by lite20** [comment]
It's on the gitbooks. This patch includes a link to it in the readme. It's under progress still but many have contributed so far.

**Comment by piranna** [comment]
Could you point me to the git repo? I could be able to include it on the NodeOS organization if it's not already there...

**Comment by lite20** [comment]
It's hosted by Gitbooks. (Gitbooks hosts the repo) but i cab import from gitbooks onto a github repo if you would like? Just pass me the URL to the repo to use and ensure I have sufficient permissions

**Comment by piranna** [comment]
> i cab import from gitbooks onto a github repo if you would like?

Yes please.


> Just pass me the URL to the repo to use and ensure I have sufficient permissions

Try to create it on the NodeOS org, if you can't tell me the name you want it to have and I'll do it for you.

**Comment by lite20** [comment]
> if you can't tell me the name you want it

Insufficient permissions :P the name "Docs" or "wiki" should be fine.

**Comment by piranna** [comment]
> Insufficient permissions :P the name "Docs" or "wiki" should be fine.

Will it be the wiki? A book? What?

**Comment by lite20** [comment]
Yes lol it is the wiki. Gitbooks just provides a nicer interface to skim through it all and nice multilingual support but yes it's just the wiki.

**Comment by piranna** [comment]
Create a repo in your account and I'll move it later to NodeOS org.

**Comment by lite20** [comment]
Okay. Will do in a second

**Comment by lite20** [comment]
[done](https://github.com/lite20/docs)

**Comment by piranna** [comment]
> done

That's cool! Does it have the full content of the wiki in GitBook format? Can be able to fully remove the wiki itself?

**Comment by piranna** [comment]
Give me administrator permissions so I can move it to NodeOS organization.

**Comment by lite20** [comment]
@piranna yup, but I'd hold on to it just to make sure everything's copied over, but yes I did import the entire wiki, just not all the content is available yet. (only what's been revised is).

**Comment by piranna** [comment]
Maybe we can remove the pages that are already ported?

**Comment by lite20** [comment]
@piranna sure!

**Comment by lite20** [comment]
@piranna I've given you admin rights on the repository. Go ahead and transfer it to NodeOS and let me know when you've done so. I'll finalize the transfer on gitbooks end, then proceed to remove what's already been ported and make the rest of the doc available.

**Comment by piranna** [comment]
How do you plan I do the transfer? Any suggestion?

**Comment by piranna** [comment]
I did not found the tab for the administration so I could be able to do the transfer, so I finally did just a fork of it :-) Should the docs link point to GitBooks or to the repo? Should we remove the wiki now and point people to the docs repo instead for changes?

**Comment by lite20** [comment]
yes it should point to the gitbooks. Contributors can be lead from the gitbooks to the repo. Yes, we may remove the wiki now!

**Comment by lite20** [comment]
I can't see a settings tab for the forked repo, I may need administrative permissions. The transfer would be performed from the settings tab on the lite20 repo. It doesn't let me transfer it as I don't have  the needed permissions on NodeOS (I guess you need the same level of perms required to create a repo in the org). I simply need to add this webhook to the repo and we're done:

https://git.gitbook.com/github?book=nodeos%2Fnodeos&username=lite20&token=971a4300-d092-48b4-a98a-1fae8ab67343

**Comment by piranna** [comment]
I've pointed the URL to the GitBook landing page and merged. I think we should left the wiki for things like the dependencies tree and left the [docs](https://github.com/NodeOS/docs) repo for more formal and static docs, like design architecture and so. What we should do is to remove from the wiki the pages already ported to the `docs` repo, at least on the english language with no translations, just for cleaning it and remove old things.

I've also added the webhook, it should work now. You can be able to delete your repo if you want.

**Pull request merged**
