### PR TITLE
Remove QEMU

### PR DESCRIPTION
**Pull request by lite20**
This removes QEMU from the NodeOS build process. **Please review the changes.**

### CODE REVIEW

**Comment by lite20** [comment]
If you can, please run the build process and see that all is clear. If it is, you may merge it, or let me know and I'll merge it (has to be done manually) I'm off to bed! Thank you!

**Comment by piranna** [comment]
Could you be able to remove the blank line removals? Beside that I don't think there's too much more for it (only the location path of the QEmu executable used by the test and start scripts), and the patch can be used as guideline to create the npm package :-)

**Comment by lite20** [comment]
Yeah sure I'll get to work on that

**Comment by piranna** [comment]
:+1:

**Comment by lite20** [comment]
Alright. All is fixed. May I merge?

**Comment by piranna** [comment]
Now it's good, thank you ;-) I have some pending changes that I would like to merge previously to this one. While I'm working on them, could you be able to pick you changes and create a new project and npm `qemu` module with them? You can get them from https://github.com/NodeOS/NodeOS/pull/214/files. On a first step is not necesary to use `prebuild` and it's ok just download and compile it as it's currently done (only that on an independent dependency, not as part of NodeOS build process), we can add support for it later :-)

**Comment by piranna** [comment]
Please remove too the `JOBS` constant and the `targetList` array, since they are only being used to compile QEmu and now that's removed they are useless (obviously you'll need them when you'll create the `qemu` module... :-D ).

**Comment by piranna** [comment]
And the `child_process` and the `os` requires, too :-P

**Comment by lite20** [comment]
Okay so I ought to finish this now that I have some free time. Would be easier to restart since your commits broke compatibility with this patch, so I'll go reset real quick.

**Comment by piranna** [comment]
You could be able to do a rebase and don't lose your current commits...

**Pull request closed without merging**
